### ISSUE TITLE
feat: publish initial library

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia-remote-pinning#1]
initial plans at https://pl-strflt.notion.site/create-interface-API-example-for-helia-remote-pinning-library-71011845a7b9476cb95ab425bb54455c
```[tasklist]
### Tasks
- [x] Review existing code & tests with team - https://github.com/ipfs/helia-remote-pinning/pull/2
- [x] update readme - https://github.com/ipfs/helia-remote-pinning/pull/2
- [ ] add to unifiedCI for JS: https://github.com/protocol/.github/blob/master/configs/js.json
```

**Comment by BigLep** [comment]
@SgtPooki : feel free to move this somewhere else.  I am putting it here since the [design doc](https://pl-strflt.notion.site/create-interface-API-example-for-helia-remote-pinning-library-71011845a7b9476cb95ab425bb54455c) is marked as done.

Thinking on this more, things I would want to account for (especially now that DCUtR is supported):
1. We send relayed addresses for [Pin.origins](https://ipfs.github.io/pinning-services-api-spec/#section/Provider-hints/Pin.origins)
2. We should only throw an error if we didn't have any public addresses in Pin.origins AND we couldn't connect to Pin.delegates.
3. Can we produce API docs that make clear when/what errors are thrown?
4. Make sure README points to the example being created in https://github.com/ipfs-examples/helia-examples/issues/86

**Comment by SgtPooki** [comment]
step 3 has switched for unified CI: https://github.com/protocol/.github#-signing-up-for-unified-ci-is-easier-than-ever

**Comment by SgtPooki** [comment]
added web3-bot to collaborators with write perms: https://github.com/ipfs/helia-remote-pinning/settings/access?guidance_task=
